// default package
// Generated May 28, 2020 11:10:15 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblBankConnectors generated by hbm2java
 */
@Entity
@Table(name = "TBL_BANK_CONNECTORS")
public class TblBankConnectors implements java.io.Serializable {

	private BigDecimal connectorId;
	private String connectorName;
	private BigDecimal connectorStatus;
	private String connectorDesc;
	private String connectorQueueKey;

	public TblBankConnectors() {
	}

	public TblBankConnectors(BigDecimal connectorId, String connectorName, BigDecimal connectorStatus,
			String connectorQueueKey) {
		this.connectorId = connectorId;
		this.connectorName = connectorName;
		this.connectorStatus = connectorStatus;
		this.connectorQueueKey = connectorQueueKey;
	}

	public TblBankConnectors(BigDecimal connectorId, String connectorName, BigDecimal connectorStatus,
			String connectorDesc, String connectorQueueKey) {
		this.connectorId = connectorId;
		this.connectorName = connectorName;
		this.connectorStatus = connectorStatus;
		this.connectorDesc = connectorDesc;
		this.connectorQueueKey = connectorQueueKey;
	}

	@Id

	@Column(name = "CONNECTOR_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getConnectorId() {
		return this.connectorId;
	}

	public void setConnectorId(BigDecimal connectorId) {
		this.connectorId = connectorId;
	}

	@Column(name = "CONNECTOR_NAME", nullable = false, length = 200)
	public String getConnectorName() {
		return this.connectorName;
	}

	public void setConnectorName(String connectorName) {
		this.connectorName = connectorName;
	}

	@Column(name = "CONNECTOR_STATUS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getConnectorStatus() {
		return this.connectorStatus;
	}

	public void setConnectorStatus(BigDecimal connectorStatus) {
		this.connectorStatus = connectorStatus;
	}

	@Column(name = "CONNECTOR_DESC", length = 500)
	public String getConnectorDesc() {
		return this.connectorDesc;
	}

	public void setConnectorDesc(String connectorDesc) {
		this.connectorDesc = connectorDesc;
	}

	@Column(name = "CONNECTOR_QUEUE_KEY", nullable = false, length = 50)
	public String getConnectorQueueKey() {
		return this.connectorQueueKey;
	}

	public void setConnectorQueueKey(String connectorQueueKey) {
		this.connectorQueueKey = connectorQueueKey;
	}

}
