// default package
// Generated May 28, 2020 11:10:15 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblBankcodeRoute generated by hbm2java
 */
@Entity
@Table(name = "TBL_BANKCODE_ROUTE")
public class TblBankcodeRoute implements java.io.Serializable {

	private BigDecimal bankCode;
	private BigDecimal officialConnectorId;
	private BigDecimal backupConnectorId;

	public TblBankcodeRoute() {
	}

	public TblBankcodeRoute(BigDecimal bankCode, BigDecimal officialConnectorId) {
		this.bankCode = bankCode;
		this.officialConnectorId = officialConnectorId;
	}

	public TblBankcodeRoute(BigDecimal bankCode, BigDecimal officialConnectorId, BigDecimal backupConnectorId) {
		this.bankCode = bankCode;
		this.officialConnectorId = officialConnectorId;
		this.backupConnectorId = backupConnectorId;
	}

	@Id

	@Column(name = "BANK_CODE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(BigDecimal bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "OFFICIAL_CONNECTOR_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getOfficialConnectorId() {
		return this.officialConnectorId;
	}

	public void setOfficialConnectorId(BigDecimal officialConnectorId) {
		this.officialConnectorId = officialConnectorId;
	}

	@Column(name = "BACKUP_CONNECTOR_ID", precision = 22, scale = 0)
	public BigDecimal getBackupConnectorId() {
		return this.backupConnectorId;
	}

	public void setBackupConnectorId(BigDecimal backupConnectorId) {
		this.backupConnectorId = backupConnectorId;
	}

}
