// default package
// Generated May 28, 2020 11:10:15 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblMoneyTransferCheckUser generated by hbm2java
 */
@Entity
@Table(name = "TBL_MONEY_TRANSFER_CHECK_USER")
public class TblMoneyTransferCheckUser implements java.io.Serializable {

	private TblMoneyTransferCheckUserId id;

	public TblMoneyTransferCheckUser() {
	}

	public TblMoneyTransferCheckUser(TblMoneyTransferCheckUserId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "requestId", column = @Column(name = "REQUEST_ID", nullable = false, length = 50)),
			@AttributeOverride(name = "requestTime", column = @Column(name = "REQUEST_TIME", length = 7)),
			@AttributeOverride(name = "partnerCode", column = @Column(name = "PARTNER_CODE", length = 20)),
			@AttributeOverride(name = "operation", column = @Column(name = "OPERATION", length = 4)),
			@AttributeOverride(name = "bankNo", column = @Column(name = "BANK_NO", length = 20)),
			@AttributeOverride(name = "accNo", column = @Column(name = "ACC_NO", length = 50)),
			@AttributeOverride(name = "accType", column = @Column(name = "ACC_TYPE", length = 1)),
			@AttributeOverride(name = "imtResponseStatus", column = @Column(name = "IMT_RESPONSE_STATUS", precision = 4, scale = 0)),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS", precision = 1, scale = 0)),
			@AttributeOverride(name = "charge", column = @Column(name = "CHARGE", precision = 1, scale = 0)),
			@AttributeOverride(name = "createdAt", column = @Column(name = "CREATED_AT", length = 7)),
			@AttributeOverride(name = "updatedAt", column = @Column(name = "UPDATED_AT", length = 7)),
			@AttributeOverride(name = "accName", column = @Column(name = "ACC_NAME", length = 50)) })
	public TblMoneyTransferCheckUserId getId() {
		return this.id;
	}

	public void setId(TblMoneyTransferCheckUserId id) {
		this.id = id;
	}

}
