// default package
// Generated May 28, 2020 11:10:15 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblMoneyTransferCheckUserId generated by hbm2java
 */
@Embeddable
public class TblMoneyTransferCheckUserId implements java.io.Serializable {

	private String requestId;
	private Date requestTime;
	private String partnerCode;
	private String operation;
	private String bankNo;
	private String accNo;
	private String accType;
	private Short imtResponseStatus;
	private Boolean status;
	private Boolean charge;
	private Date createdAt;
	private Date updatedAt;
	private String accName;

	public TblMoneyTransferCheckUserId() {
	}

	public TblMoneyTransferCheckUserId(String requestId) {
		this.requestId = requestId;
	}

	public TblMoneyTransferCheckUserId(String requestId, Date requestTime, String partnerCode, String operation,
			String bankNo, String accNo, String accType, Short imtResponseStatus, Boolean status, Boolean charge,
			Date createdAt, Date updatedAt, String accName) {
		this.requestId = requestId;
		this.requestTime = requestTime;
		this.partnerCode = partnerCode;
		this.operation = operation;
		this.bankNo = bankNo;
		this.accNo = accNo;
		this.accType = accType;
		this.imtResponseStatus = imtResponseStatus;
		this.status = status;
		this.charge = charge;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.accName = accName;
	}

	@Column(name = "REQUEST_ID", nullable = false, length = 50)
	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	@Column(name = "REQUEST_TIME", length = 7)
	public Date getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	@Column(name = "PARTNER_CODE", length = 20)
	public String getPartnerCode() {
		return this.partnerCode;
	}

	public void setPartnerCode(String partnerCode) {
		this.partnerCode = partnerCode;
	}

	@Column(name = "OPERATION", length = 4)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "BANK_NO", length = 20)
	public String getBankNo() {
		return this.bankNo;
	}

	public void setBankNo(String bankNo) {
		this.bankNo = bankNo;
	}

	@Column(name = "ACC_NO", length = 50)
	public String getAccNo() {
		return this.accNo;
	}

	public void setAccNo(String accNo) {
		this.accNo = accNo;
	}

	@Column(name = "ACC_TYPE", length = 1)
	public String getAccType() {
		return this.accType;
	}

	public void setAccType(String accType) {
		this.accType = accType;
	}

	@Column(name = "IMT_RESPONSE_STATUS", precision = 4, scale = 0)
	public Short getImtResponseStatus() {
		return this.imtResponseStatus;
	}

	public void setImtResponseStatus(Short imtResponseStatus) {
		this.imtResponseStatus = imtResponseStatus;
	}

	@Column(name = "STATUS", precision = 1, scale = 0)
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "CHARGE", precision = 1, scale = 0)
	public Boolean getCharge() {
		return this.charge;
	}

	public void setCharge(Boolean charge) {
		this.charge = charge;
	}

	@Column(name = "CREATED_AT", length = 7)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "UPDATED_AT", length = 7)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "ACC_NAME", length = 50)
	public String getAccName() {
		return this.accName;
	}

	public void setAccName(String accName) {
		this.accName = accName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblMoneyTransferCheckUserId))
			return false;
		TblMoneyTransferCheckUserId castOther = (TblMoneyTransferCheckUserId) other;

		return ((this.getRequestId() == castOther.getRequestId()) || (this.getRequestId() != null
				&& castOther.getRequestId() != null && this.getRequestId().equals(castOther.getRequestId())))
				&& ((this.getRequestTime() == castOther.getRequestTime())
						|| (this.getRequestTime() != null && castOther.getRequestTime() != null
								&& this.getRequestTime().equals(castOther.getRequestTime())))
				&& ((this.getPartnerCode() == castOther.getPartnerCode())
						|| (this.getPartnerCode() != null && castOther.getPartnerCode() != null
								&& this.getPartnerCode().equals(castOther.getPartnerCode())))
				&& ((this.getOperation() == castOther.getOperation()) || (this.getOperation() != null
						&& castOther.getOperation() != null && this.getOperation().equals(castOther.getOperation())))
				&& ((this.getBankNo() == castOther.getBankNo()) || (this.getBankNo() != null
						&& castOther.getBankNo() != null && this.getBankNo().equals(castOther.getBankNo())))
				&& ((this.getAccNo() == castOther.getAccNo()) || (this.getAccNo() != null
						&& castOther.getAccNo() != null && this.getAccNo().equals(castOther.getAccNo())))
				&& ((this.getAccType() == castOther.getAccType()) || (this.getAccType() != null
						&& castOther.getAccType() != null && this.getAccType().equals(castOther.getAccType())))
				&& ((this.getImtResponseStatus() == castOther.getImtResponseStatus())
						|| (this.getImtResponseStatus() != null && castOther.getImtResponseStatus() != null
								&& this.getImtResponseStatus().equals(castOther.getImtResponseStatus())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getCharge() == castOther.getCharge()) || (this.getCharge() != null
						&& castOther.getCharge() != null && this.getCharge().equals(castOther.getCharge())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getAccName() == castOther.getAccName()) || (this.getAccName() != null
						&& castOther.getAccName() != null && this.getAccName().equals(castOther.getAccName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRequestId() == null ? 0 : this.getRequestId().hashCode());
		result = 37 * result + (getRequestTime() == null ? 0 : this.getRequestTime().hashCode());
		result = 37 * result + (getPartnerCode() == null ? 0 : this.getPartnerCode().hashCode());
		result = 37 * result + (getOperation() == null ? 0 : this.getOperation().hashCode());
		result = 37 * result + (getBankNo() == null ? 0 : this.getBankNo().hashCode());
		result = 37 * result + (getAccNo() == null ? 0 : this.getAccNo().hashCode());
		result = 37 * result + (getAccType() == null ? 0 : this.getAccType().hashCode());
		result = 37 * result + (getImtResponseStatus() == null ? 0 : this.getImtResponseStatus().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getCharge() == null ? 0 : this.getCharge().hashCode());
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + (getAccName() == null ? 0 : this.getAccName().hashCode());
		return result;
	}

}
