// default package
// Generated May 28, 2020 11:10:15 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblMoneyTranTempFee generated by hbm2java
 */
@Entity
@Table(name = "TBL_MONEY_TRAN_TEMP_FEE")
public class TblMoneyTranTempFee implements java.io.Serializable {

	private long id;
	private String tempFeeCode;
	private String tempFeeName;
	private Boolean typeTempFee;
	private Boolean status;
	private String userRequest;
	private String userApprove;
	private Date timeApprove;
	private Date timeUse;
	private Boolean typeFee;
	private Long fixedFee;
	private Double ratioFee;
	private Long minFee;
	private Long maxFee;
	private Date createdAt;
	private Boolean lockStatus;
	private String userUpdate;
	private Date timeUpdate;
	private String description;
	private Date updatedAt;
	private Long checkFee;
	private Long fromFee;
	private Long toFee;
	private Short tempReplace;

	public TblMoneyTranTempFee() {
	}

	public TblMoneyTranTempFee(long id, String tempFeeCode) {
		this.id = id;
		this.tempFeeCode = tempFeeCode;
	}

	public TblMoneyTranTempFee(long id, String tempFeeCode, String tempFeeName, Boolean typeTempFee, Boolean status,
			String userRequest, String userApprove, Date timeApprove, Date timeUse, Boolean typeFee, Long fixedFee,
			Double ratioFee, Long minFee, Long maxFee, Date createdAt, Boolean lockStatus, String userUpdate,
			Date timeUpdate, String description, Date updatedAt, Long checkFee, Long fromFee, Long toFee,
			Short tempReplace) {
		this.id = id;
		this.tempFeeCode = tempFeeCode;
		this.tempFeeName = tempFeeName;
		this.typeTempFee = typeTempFee;
		this.status = status;
		this.userRequest = userRequest;
		this.userApprove = userApprove;
		this.timeApprove = timeApprove;
		this.timeUse = timeUse;
		this.typeFee = typeFee;
		this.fixedFee = fixedFee;
		this.ratioFee = ratioFee;
		this.minFee = minFee;
		this.maxFee = maxFee;
		this.createdAt = createdAt;
		this.lockStatus = lockStatus;
		this.userUpdate = userUpdate;
		this.timeUpdate = timeUpdate;
		this.description = description;
		this.updatedAt = updatedAt;
		this.checkFee = checkFee;
		this.fromFee = fromFee;
		this.toFee = toFee;
		this.tempReplace = tempReplace;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 11, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "TEMP_FEE_CODE", nullable = false, length = 50)
	public String getTempFeeCode() {
		return this.tempFeeCode;
	}

	public void setTempFeeCode(String tempFeeCode) {
		this.tempFeeCode = tempFeeCode;
	}

	@Column(name = "TEMP_FEE_NAME", length = 200)
	public String getTempFeeName() {
		return this.tempFeeName;
	}

	public void setTempFeeName(String tempFeeName) {
		this.tempFeeName = tempFeeName;
	}

	@Column(name = "TYPE_TEMP_FEE", precision = 1, scale = 0)
	public Boolean getTypeTempFee() {
		return this.typeTempFee;
	}

	public void setTypeTempFee(Boolean typeTempFee) {
		this.typeTempFee = typeTempFee;
	}

	@Column(name = "STATUS", precision = 1, scale = 0)
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "USER_REQUEST", length = 30)
	public String getUserRequest() {
		return this.userRequest;
	}

	public void setUserRequest(String userRequest) {
		this.userRequest = userRequest;
	}

	@Column(name = "USER_APPROVE", length = 30)
	public String getUserApprove() {
		return this.userApprove;
	}

	public void setUserApprove(String userApprove) {
		this.userApprove = userApprove;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TIME_APPROVE", length = 7)
	public Date getTimeApprove() {
		return this.timeApprove;
	}

	public void setTimeApprove(Date timeApprove) {
		this.timeApprove = timeApprove;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TIME_USE", length = 7)
	public Date getTimeUse() {
		return this.timeUse;
	}

	public void setTimeUse(Date timeUse) {
		this.timeUse = timeUse;
	}

	@Column(name = "TYPE_FEE", precision = 1, scale = 0)
	public Boolean getTypeFee() {
		return this.typeFee;
	}

	public void setTypeFee(Boolean typeFee) {
		this.typeFee = typeFee;
	}

	@Column(name = "FIXED_FEE", precision = 11, scale = 0)
	public Long getFixedFee() {
		return this.fixedFee;
	}

	public void setFixedFee(Long fixedFee) {
		this.fixedFee = fixedFee;
	}

	@Column(name = "RATIO_FEE", precision = 126, scale = 0)
	public Double getRatioFee() {
		return this.ratioFee;
	}

	public void setRatioFee(Double ratioFee) {
		this.ratioFee = ratioFee;
	}

	@Column(name = "MIN_FEE", precision = 11, scale = 0)
	public Long getMinFee() {
		return this.minFee;
	}

	public void setMinFee(Long minFee) {
		this.minFee = minFee;
	}

	@Column(name = "MAX_FEE", precision = 11, scale = 0)
	public Long getMaxFee() {
		return this.maxFee;
	}

	public void setMaxFee(Long maxFee) {
		this.maxFee = maxFee;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_AT", length = 7)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "LOCK_STATUS", precision = 1, scale = 0)
	public Boolean getLockStatus() {
		return this.lockStatus;
	}

	public void setLockStatus(Boolean lockStatus) {
		this.lockStatus = lockStatus;
	}

	@Column(name = "USER_UPDATE", length = 30)
	public String getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(String userUpdate) {
		this.userUpdate = userUpdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TIME_UPDATE", length = 7)
	public Date getTimeUpdate() {
		return this.timeUpdate;
	}

	public void setTimeUpdate(Date timeUpdate) {
		this.timeUpdate = timeUpdate;
	}

	@Column(name = "DESCRIPTION", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATED_AT", length = 7)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "CHECK_FEE", precision = 11, scale = 0)
	public Long getCheckFee() {
		return this.checkFee;
	}

	public void setCheckFee(Long checkFee) {
		this.checkFee = checkFee;
	}

	@Column(name = "FROM_FEE", precision = 11, scale = 0)
	public Long getFromFee() {
		return this.fromFee;
	}

	public void setFromFee(Long fromFee) {
		this.fromFee = fromFee;
	}

	@Column(name = "TO_FEE", precision = 11, scale = 0)
	public Long getToFee() {
		return this.toFee;
	}

	public void setToFee(Long toFee) {
		this.toFee = toFee;
	}

	@Column(name = "TEMP_REPLACE", precision = 3, scale = 0)
	public Short getTempReplace() {
		return this.tempReplace;
	}

	public void setTempReplace(Short tempReplace) {
		this.tempReplace = tempReplace;
	}

}
