// default package
// Generated May 28, 2020 11:10:15 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblMoneyTransferPartner generated by hbm2java
 */
@Entity
@Table(name = "TBL_MONEY_TRANSFER_PARTNER")
public class TblMoneyTransferPartner implements java.io.Serializable {

	private long partnerId;
	private String partnerCode;
	private String partnerName;
	private String connectIp;
	private String emailDs;
	private String emailTo;
	private String emailCc;
	private String address;
	private Boolean status;
	private Boolean isDeleted;
	private Date createdAt;
	private Date updatedAt;
	private Boolean typeLimit;
	private Long currentLimit;
	private Long availableLimit;
	private Long holdingLimit;
	private Date limitDate;
	private String phone;
	private Long charge;
	private String phoneNo;
	private Boolean statusCheckAcc;
	private Boolean statusTransfer;
	private BigDecimal chargeType;
	private String callbackApi;
	private BigDecimal limitBudget;
	private String partnerPublicKey;
	private Integer verifySig;
	private BigDecimal alertLimit;

	public TblMoneyTransferPartner() {
	}

	public TblMoneyTransferPartner(long partnerId, String partnerCode, String partnerName) {
		this.partnerId = partnerId;
		this.partnerCode = partnerCode;
		this.partnerName = partnerName;
	}

	public TblMoneyTransferPartner(long partnerId, String partnerCode, String partnerName, String connectIp,
			String emailDs, String emailTo, String emailCc, String address, Boolean status, Boolean isDeleted,
			Date createdAt, Date updatedAt, Boolean typeLimit, Long currentLimit, Long availableLimit,
			Long holdingLimit, Date limitDate, String phone, Long charge, String phoneNo, Boolean statusCheckAcc,
			Boolean statusTransfer, BigDecimal chargeType, String callbackApi, BigDecimal limitBudget,
			String partnerPublicKey, Integer verifySig, BigDecimal alertLimit) {
		this.partnerId = partnerId;
		this.partnerCode = partnerCode;
		this.partnerName = partnerName;
		this.connectIp = connectIp;
		this.emailDs = emailDs;
		this.emailTo = emailTo;
		this.emailCc = emailCc;
		this.address = address;
		this.status = status;
		this.isDeleted = isDeleted;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.typeLimit = typeLimit;
		this.currentLimit = currentLimit;
		this.availableLimit = availableLimit;
		this.holdingLimit = holdingLimit;
		this.limitDate = limitDate;
		this.phone = phone;
		this.charge = charge;
		this.phoneNo = phoneNo;
		this.statusCheckAcc = statusCheckAcc;
		this.statusTransfer = statusTransfer;
		this.chargeType = chargeType;
		this.callbackApi = callbackApi;
		this.limitBudget = limitBudget;
		this.partnerPublicKey = partnerPublicKey;
		this.verifySig = verifySig;
		this.alertLimit = alertLimit;
	}

	@Id

	@Column(name = "PARTNER_ID", unique = true, nullable = false, precision = 11, scale = 0)
	public long getPartnerId() {
		return this.partnerId;
	}

	public void setPartnerId(long partnerId) {
		this.partnerId = partnerId;
	}

	@Column(name = "PARTNER_CODE", nullable = false, length = 20)
	public String getPartnerCode() {
		return this.partnerCode;
	}

	public void setPartnerCode(String partnerCode) {
		this.partnerCode = partnerCode;
	}

	@Column(name = "PARTNER_NAME", nullable = false, length = 200)
	public String getPartnerName() {
		return this.partnerName;
	}

	public void setPartnerName(String partnerName) {
		this.partnerName = partnerName;
	}

	@Column(name = "CONNECT_IP", length = 200)
	public String getConnectIp() {
		return this.connectIp;
	}

	public void setConnectIp(String connectIp) {
		this.connectIp = connectIp;
	}

	@Column(name = "EMAIL_DS", length = 500)
	public String getEmailDs() {
		return this.emailDs;
	}

	public void setEmailDs(String emailDs) {
		this.emailDs = emailDs;
	}

	@Column(name = "EMAIL_TO", length = 100)
	public String getEmailTo() {
		return this.emailTo;
	}

	public void setEmailTo(String emailTo) {
		this.emailTo = emailTo;
	}

	@Column(name = "EMAIL_CC", length = 500)
	public String getEmailCc() {
		return this.emailCc;
	}

	public void setEmailCc(String emailCc) {
		this.emailCc = emailCc;
	}

	@Column(name = "ADDRESS", length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "STATUS", precision = 1, scale = 0)
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "IS_DELETED", precision = 1, scale = 0)
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_AT", length = 7)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATED_AT", length = 7)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "TYPE_LIMIT", precision = 1, scale = 0)
	public Boolean getTypeLimit() {
		return this.typeLimit;
	}

	public void setTypeLimit(Boolean typeLimit) {
		this.typeLimit = typeLimit;
	}

	@Column(name = "CURRENT_LIMIT", precision = 11, scale = 0)
	public Long getCurrentLimit() {
		return this.currentLimit;
	}

	public void setCurrentLimit(Long currentLimit) {
		this.currentLimit = currentLimit;
	}

	@Column(name = "AVAILABLE_LIMIT", precision = 11, scale = 0)
	public Long getAvailableLimit() {
		return this.availableLimit;
	}

	public void setAvailableLimit(Long availableLimit) {
		this.availableLimit = availableLimit;
	}

	@Column(name = "HOLDING_LIMIT", precision = 11, scale = 0)
	public Long getHoldingLimit() {
		return this.holdingLimit;
	}

	public void setHoldingLimit(Long holdingLimit) {
		this.holdingLimit = holdingLimit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LIMIT_DATE", length = 7)
	public Date getLimitDate() {
		return this.limitDate;
	}

	public void setLimitDate(Date limitDate) {
		this.limitDate = limitDate;
	}

	@Column(name = "PHONE", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "CHARGE", precision = 11, scale = 0)
	public Long getCharge() {
		return this.charge;
	}

	public void setCharge(Long charge) {
		this.charge = charge;
	}

	@Column(name = "PHONE_NO", length = 15)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "STATUS_CHECK_ACC", precision = 1, scale = 0)
	public Boolean getStatusCheckAcc() {
		return this.statusCheckAcc;
	}

	public void setStatusCheckAcc(Boolean statusCheckAcc) {
		this.statusCheckAcc = statusCheckAcc;
	}

	@Column(name = "STATUS_TRANSFER", precision = 1, scale = 0)
	public Boolean getStatusTransfer() {
		return this.statusTransfer;
	}

	public void setStatusTransfer(Boolean statusTransfer) {
		this.statusTransfer = statusTransfer;
	}

	@Column(name = "CHARGE_TYPE", precision = 22, scale = 0)
	public BigDecimal getChargeType() {
		return this.chargeType;
	}

	public void setChargeType(BigDecimal chargeType) {
		this.chargeType = chargeType;
	}

	@Column(name = "CALLBACK_API", length = 200)
	public String getCallbackApi() {
		return this.callbackApi;
	}

	public void setCallbackApi(String callbackApi) {
		this.callbackApi = callbackApi;
	}

	@Column(name = "LIMIT_BUDGET", precision = 22, scale = 0)
	public BigDecimal getLimitBudget() {
		return this.limitBudget;
	}

	public void setLimitBudget(BigDecimal limitBudget) {
		this.limitBudget = limitBudget;
	}

	@Column(name = "PARTNER_PUBLIC_KEY", length = 2000)
	public String getPartnerPublicKey() {
		return this.partnerPublicKey;
	}

	public void setPartnerPublicKey(String partnerPublicKey) {
		this.partnerPublicKey = partnerPublicKey;
	}

	@Column(name = "VERIFY_SIG", precision = 8, scale = 0)
	public Integer getVerifySig() {
		return this.verifySig;
	}

	public void setVerifySig(Integer verifySig) {
		this.verifySig = verifySig;
	}

	@Column(name = "ALERT_LIMIT", precision = 22, scale = 0)
	public BigDecimal getAlertLimit() {
		return this.alertLimit;
	}

	public void setAlertLimit(BigDecimal alertLimit) {
		this.alertLimit = alertLimit;
	}

}
