// default package
// Generated May 28, 2020 11:10:15 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblMoneyTransferReqLog2 generated by hbm2java
 */
@Entity
@Table(name = "TBL_MONEY_TRANSFER_REQ_LOG2")
public class TblMoneyTransferReqLog2 implements java.io.Serializable {

	private BigDecimal rowId;
	private String requestId;
	private Date requestTime;
	private String partnerCode;
	private String operation;
	private String bankNo;
	private String accNo;
	private String accType;
	private String referenceId;
	private Double amount;
	private String imtResponse;
	private String gwResponse;
	private Date createdAt;
	private Date updatedAt;
	private String appId;
	private String bankStatus;
	private String bankRequestId;
	private Boolean charged;

	public TblMoneyTransferReqLog2() {
	}

	public TblMoneyTransferReqLog2(BigDecimal rowId, String requestId) {
		this.rowId = rowId;
		this.requestId = requestId;
	}

	public TblMoneyTransferReqLog2(BigDecimal rowId, String requestId, Date requestTime, String partnerCode,
			String operation, String bankNo, String accNo, String accType, String referenceId, Double amount,
			String imtResponse, String gwResponse, Date createdAt, Date updatedAt, String appId, String bankStatus,
			String bankRequestId, Boolean charged) {
		this.rowId = rowId;
		this.requestId = requestId;
		this.requestTime = requestTime;
		this.partnerCode = partnerCode;
		this.operation = operation;
		this.bankNo = bankNo;
		this.accNo = accNo;
		this.accType = accType;
		this.referenceId = referenceId;
		this.amount = amount;
		this.imtResponse = imtResponse;
		this.gwResponse = gwResponse;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.appId = appId;
		this.bankStatus = bankStatus;
		this.bankRequestId = bankRequestId;
		this.charged = charged;
	}

	@Id

	@Column(name = "ROW_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRowId() {
		return this.rowId;
	}

	public void setRowId(BigDecimal rowId) {
		this.rowId = rowId;
	}

	@Column(name = "REQUEST_ID", nullable = false, length = 50)
	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REQUEST_TIME", length = 7)
	public Date getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	@Column(name = "PARTNER_CODE", length = 20)
	public String getPartnerCode() {
		return this.partnerCode;
	}

	public void setPartnerCode(String partnerCode) {
		this.partnerCode = partnerCode;
	}

	@Column(name = "OPERATION", length = 4)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "BANK_NO", length = 20)
	public String getBankNo() {
		return this.bankNo;
	}

	public void setBankNo(String bankNo) {
		this.bankNo = bankNo;
	}

	@Column(name = "ACC_NO", length = 50)
	public String getAccNo() {
		return this.accNo;
	}

	public void setAccNo(String accNo) {
		this.accNo = accNo;
	}

	@Column(name = "ACC_TYPE", length = 1)
	public String getAccType() {
		return this.accType;
	}

	public void setAccType(String accType) {
		this.accType = accType;
	}

	@Column(name = "REFERENCE_ID", length = 50)
	public String getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

	@Column(name = "AMOUNT", precision = 30, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "IMT_RESPONSE", length = 2000)
	public String getImtResponse() {
		return this.imtResponse;
	}

	public void setImtResponse(String imtResponse) {
		this.imtResponse = imtResponse;
	}

	@Column(name = "GW_RESPONSE", length = 2000)
	public String getGwResponse() {
		return this.gwResponse;
	}

	public void setGwResponse(String gwResponse) {
		this.gwResponse = gwResponse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_AT", length = 7)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATED_AT", length = 7)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "APP_ID", length = 22)
	public String getAppId() {
		return this.appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	@Column(name = "BANK_STATUS", length = 10)
	public String getBankStatus() {
		return this.bankStatus;
	}

	public void setBankStatus(String bankStatus) {
		this.bankStatus = bankStatus;
	}

	@Column(name = "BANK_REQUEST_ID", length = 50)
	public String getBankRequestId() {
		return this.bankRequestId;
	}

	public void setBankRequestId(String bankRequestId) {
		this.bankRequestId = bankRequestId;
	}

	@Column(name = "CHARGED", precision = 1, scale = 0)
	public Boolean getCharged() {
		return this.charged;
	}

	public void setCharged(Boolean charged) {
		this.charged = charged;
	}

}
