// default package
// Generated May 28, 2020 11:10:15 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TblMoneyTransferTransaction generated by hbm2java
 */
@Entity
@Table(name = "TBL_MONEY_TRANSFER_TRANSACTION", uniqueConstraints = @UniqueConstraint(columnNames = { "TRANS_ID",
		"REFERENCE_ID" }))
public class TblMoneyTransferTransaction implements java.io.Serializable {

	private String transId;
	private String referenceId;
	private String requestId;
	private Date requestTime;
	private String partnerCode;
	private String bankNo;
	private String accNo;
	private Boolean accType;
	private String memo;
	private String gwStatusResponse;
	private String imtStatusResponse;
	private Long status;
	private Date transTime;
	private Date createdAt;
	private Date updatedAt;
	private BigDecimal isUpdate;
	private Double requestAmount;
	private Double transferRealAmount;
	private Double transferFeeAmount;
	private Boolean transferFeeType;
	private String accName;
	private String appId;
	private Boolean isSend;
	private String messageNo;
	private Date gwDateOfTransaction;
	private Long gwTimeOfTransaction;
	private Date updatedEndStatusAt;
	private Long previousStatus;
	private String branchNo;
	private BigDecimal scanSucces;
	private BigDecimal connectorId;
	private BigDecimal bankResponseStatus;
	private String bankDescription;
	private String bankRequestId;
	private BigDecimal chanel;
	private String remark;
	private BigDecimal isRefund;
	private Date refundDate;

	public TblMoneyTransferTransaction() {
	}

	public TblMoneyTransferTransaction(String transId, BigDecimal scanSucces) {
		this.transId = transId;
		this.scanSucces = scanSucces;
	}

	public TblMoneyTransferTransaction(String transId, String referenceId, String requestId, Date requestTime,
			String partnerCode, String bankNo, String accNo, Boolean accType, String memo, String gwStatusResponse,
			String imtStatusResponse, Long status, Date transTime, Date createdAt, Date updatedAt, BigDecimal isUpdate,
			Double requestAmount, Double transferRealAmount, Double transferFeeAmount, Boolean transferFeeType,
			String accName, String appId, Boolean isSend, String messageNo, Date gwDateOfTransaction,
			Long gwTimeOfTransaction, Date updatedEndStatusAt, Long previousStatus, String branchNo,
			BigDecimal scanSucces, BigDecimal connectorId, BigDecimal bankResponseStatus, String bankDescription,
			String bankRequestId, BigDecimal chanel, String remark, BigDecimal isRefund, Date refundDate) {
		this.transId = transId;
		this.referenceId = referenceId;
		this.requestId = requestId;
		this.requestTime = requestTime;
		this.partnerCode = partnerCode;
		this.bankNo = bankNo;
		this.accNo = accNo;
		this.accType = accType;
		this.memo = memo;
		this.gwStatusResponse = gwStatusResponse;
		this.imtStatusResponse = imtStatusResponse;
		this.status = status;
		this.transTime = transTime;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.isUpdate = isUpdate;
		this.requestAmount = requestAmount;
		this.transferRealAmount = transferRealAmount;
		this.transferFeeAmount = transferFeeAmount;
		this.transferFeeType = transferFeeType;
		this.accName = accName;
		this.appId = appId;
		this.isSend = isSend;
		this.messageNo = messageNo;
		this.gwDateOfTransaction = gwDateOfTransaction;
		this.gwTimeOfTransaction = gwTimeOfTransaction;
		this.updatedEndStatusAt = updatedEndStatusAt;
		this.previousStatus = previousStatus;
		this.branchNo = branchNo;
		this.scanSucces = scanSucces;
		this.connectorId = connectorId;
		this.bankResponseStatus = bankResponseStatus;
		this.bankDescription = bankDescription;
		this.bankRequestId = bankRequestId;
		this.chanel = chanel;
		this.remark = remark;
		this.isRefund = isRefund;
		this.refundDate = refundDate;
	}

	@Id

	@Column(name = "TRANS_ID", unique = true, nullable = false, length = 50)
	public String getTransId() {
		return this.transId;
	}

	public void setTransId(String transId) {
		this.transId = transId;
	}

	@Column(name = "REFERENCE_ID", length = 50)
	public String getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

	@Column(name = "REQUEST_ID", length = 50)
	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REQUEST_TIME", length = 7)
	public Date getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	@Column(name = "PARTNER_CODE", length = 20)
	public String getPartnerCode() {
		return this.partnerCode;
	}

	public void setPartnerCode(String partnerCode) {
		this.partnerCode = partnerCode;
	}

	@Column(name = "BANK_NO", length = 20)
	public String getBankNo() {
		return this.bankNo;
	}

	public void setBankNo(String bankNo) {
		this.bankNo = bankNo;
	}

	@Column(name = "ACC_NO", length = 30)
	public String getAccNo() {
		return this.accNo;
	}

	public void setAccNo(String accNo) {
		this.accNo = accNo;
	}

	@Column(name = "ACC_TYPE", precision = 1, scale = 0)
	public Boolean getAccType() {
		return this.accType;
	}

	public void setAccType(Boolean accType) {
		this.accType = accType;
	}

	@Column(name = "MEMO", length = 300)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "GW_STATUS_RESPONSE", length = 10)
	public String getGwStatusResponse() {
		return this.gwStatusResponse;
	}

	public void setGwStatusResponse(String gwStatusResponse) {
		this.gwStatusResponse = gwStatusResponse;
	}

	@Column(name = "IMT_STATUS_RESPONSE", length = 10)
	public String getImtStatusResponse() {
		return this.imtStatusResponse;
	}

	public void setImtStatusResponse(String imtStatusResponse) {
		this.imtStatusResponse = imtStatusResponse;
	}

	@Column(name = "STATUS", precision = 11, scale = 0)
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TRANS_TIME", length = 7)
	public Date getTransTime() {
		return this.transTime;
	}

	public void setTransTime(Date transTime) {
		this.transTime = transTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_AT", length = 7)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATED_AT", length = 7)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "IS_UPDATE", precision = 22, scale = 0)
	public BigDecimal getIsUpdate() {
		return this.isUpdate;
	}

	public void setIsUpdate(BigDecimal isUpdate) {
		this.isUpdate = isUpdate;
	}

	@Column(name = "REQUEST_AMOUNT", precision = 30, scale = 0)
	public Double getRequestAmount() {
		return this.requestAmount;
	}

	public void setRequestAmount(Double requestAmount) {
		this.requestAmount = requestAmount;
	}

	@Column(name = "TRANSFER_REAL_AMOUNT", precision = 30, scale = 0)
	public Double getTransferRealAmount() {
		return this.transferRealAmount;
	}

	public void setTransferRealAmount(Double transferRealAmount) {
		this.transferRealAmount = transferRealAmount;
	}

	@Column(name = "TRANSFER_FEE_AMOUNT", precision = 30, scale = 0)
	public Double getTransferFeeAmount() {
		return this.transferFeeAmount;
	}

	public void setTransferFeeAmount(Double transferFeeAmount) {
		this.transferFeeAmount = transferFeeAmount;
	}

	@Column(name = "TRANSFER_FEE_TYPE", precision = 1, scale = 0)
	public Boolean getTransferFeeType() {
		return this.transferFeeType;
	}

	public void setTransferFeeType(Boolean transferFeeType) {
		this.transferFeeType = transferFeeType;
	}

	@Column(name = "ACC_NAME", length = 50)
	public String getAccName() {
		return this.accName;
	}

	public void setAccName(String accName) {
		this.accName = accName;
	}

	@Column(name = "APP_ID", length = 22)
	public String getAppId() {
		return this.appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	@Column(name = "IS_SEND", precision = 1, scale = 0)
	public Boolean getIsSend() {
		return this.isSend;
	}

	public void setIsSend(Boolean isSend) {
		this.isSend = isSend;
	}

	@Column(name = "MESSAGE_NO", length = 100)
	public String getMessageNo() {
		return this.messageNo;
	}

	public void setMessageNo(String messageNo) {
		this.messageNo = messageNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GW_DATE_OF_TRANSACTION", length = 7)
	public Date getGwDateOfTransaction() {
		return this.gwDateOfTransaction;
	}

	public void setGwDateOfTransaction(Date gwDateOfTransaction) {
		this.gwDateOfTransaction = gwDateOfTransaction;
	}

	@Column(name = "GW_TIME_OF_TRANSACTION", precision = 11, scale = 0)
	public Long getGwTimeOfTransaction() {
		return this.gwTimeOfTransaction;
	}

	public void setGwTimeOfTransaction(Long gwTimeOfTransaction) {
		this.gwTimeOfTransaction = gwTimeOfTransaction;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATED_END_STATUS_AT", length = 7)
	public Date getUpdatedEndStatusAt() {
		return this.updatedEndStatusAt;
	}

	public void setUpdatedEndStatusAt(Date updatedEndStatusAt) {
		this.updatedEndStatusAt = updatedEndStatusAt;
	}

	@Column(name = "PREVIOUS_STATUS", precision = 11, scale = 0)
	public Long getPreviousStatus() {
		return this.previousStatus;
	}

	public void setPreviousStatus(Long previousStatus) {
		this.previousStatus = previousStatus;
	}

	@Column(name = "BRANCH_NO", length = 20)
	public String getBranchNo() {
		return this.branchNo;
	}

	public void setBranchNo(String branchNo) {
		this.branchNo = branchNo;
	}

	@Column(name = "SCAN_SUCCES", nullable = false, precision = 22, scale = 0)
	public BigDecimal getScanSucces() {
		return this.scanSucces;
	}

	public void setScanSucces(BigDecimal scanSucces) {
		this.scanSucces = scanSucces;
	}

	@Column(name = "CONNECTOR_ID", precision = 22, scale = 0)
	public BigDecimal getConnectorId() {
		return this.connectorId;
	}

	public void setConnectorId(BigDecimal connectorId) {
		this.connectorId = connectorId;
	}

	@Column(name = "BANK_RESPONSE_STATUS", precision = 22, scale = 0)
	public BigDecimal getBankResponseStatus() {
		return this.bankResponseStatus;
	}

	public void setBankResponseStatus(BigDecimal bankResponseStatus) {
		this.bankResponseStatus = bankResponseStatus;
	}

	@Column(name = "BANK_DESCRIPTION", length = 200)
	public String getBankDescription() {
		return this.bankDescription;
	}

	public void setBankDescription(String bankDescription) {
		this.bankDescription = bankDescription;
	}

	@Column(name = "BANK_REQUEST_ID", length = 50)
	public String getBankRequestId() {
		return this.bankRequestId;
	}

	public void setBankRequestId(String bankRequestId) {
		this.bankRequestId = bankRequestId;
	}

	@Column(name = "CHANEL", precision = 22, scale = 0)
	public BigDecimal getChanel() {
		return this.chanel;
	}

	public void setChanel(BigDecimal chanel) {
		this.chanel = chanel;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "IS_REFUND", precision = 1)
	public BigDecimal getIsRefund() {
		return this.isRefund;
	}

	public void setIsRefund(BigDecimal isRefund) {
		this.isRefund = isRefund;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REFUND_DATE", length = 7)
	public Date getRefundDate() {
		return this.refundDate;
	}

	public void setRefundDate(Date refundDate) {
		this.refundDate = refundDate;
	}

}
