// default package
// Generated May 28, 2020 11:10:15 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblTransactionsId generated by hbm2java
 */
@Embeddable
public class TblTransactionsId implements java.io.Serializable {

	private String username;
	private String sessionid;
	private String partnerCode;
	private String targetAccount;
	private String serviceProviderCode;
	private String providerSession;
	private String transStatus;
	private String transid;
	private BigDecimal amount;
	private Date transDate;
	private String transidRequest;
	private Date updatedDate;
	private String telcoStatus;
	private String message;
	private Date updatedCheckTime;
	private String transStatusOld;
	private Date createdDate;
	private BigDecimal topupType;
	private String telcoTransId;
	private String serviceProviderName;
	private BigDecimal recId;
	private String statusUpdate;
	private Date statusUpdateTime;

	public TblTransactionsId() {
	}

	public TblTransactionsId(String username, String sessionid, String partnerCode, String targetAccount,
			String serviceProviderCode, String providerSession, String transStatus, String transid, BigDecimal amount,
			Date transDate, String transidRequest, Date updatedDate, String telcoStatus, String message,
			Date updatedCheckTime, String transStatusOld, Date createdDate, BigDecimal topupType, String telcoTransId,
			String serviceProviderName, BigDecimal recId, String statusUpdate, Date statusUpdateTime) {
		this.username = username;
		this.sessionid = sessionid;
		this.partnerCode = partnerCode;
		this.targetAccount = targetAccount;
		this.serviceProviderCode = serviceProviderCode;
		this.providerSession = providerSession;
		this.transStatus = transStatus;
		this.transid = transid;
		this.amount = amount;
		this.transDate = transDate;
		this.transidRequest = transidRequest;
		this.updatedDate = updatedDate;
		this.telcoStatus = telcoStatus;
		this.message = message;
		this.updatedCheckTime = updatedCheckTime;
		this.transStatusOld = transStatusOld;
		this.createdDate = createdDate;
		this.topupType = topupType;
		this.telcoTransId = telcoTransId;
		this.serviceProviderName = serviceProviderName;
		this.recId = recId;
		this.statusUpdate = statusUpdate;
		this.statusUpdateTime = statusUpdateTime;
	}

	@Column(name = "USERNAME", length = 10)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "SESSIONID", length = 100)
	public String getSessionid() {
		return this.sessionid;
	}

	public void setSessionid(String sessionid) {
		this.sessionid = sessionid;
	}

	@Column(name = "PARTNER_CODE", length = 10)
	public String getPartnerCode() {
		return this.partnerCode;
	}

	public void setPartnerCode(String partnerCode) {
		this.partnerCode = partnerCode;
	}

	@Column(name = "TARGET_ACCOUNT", length = 50)
	public String getTargetAccount() {
		return this.targetAccount;
	}

	public void setTargetAccount(String targetAccount) {
		this.targetAccount = targetAccount;
	}

	@Column(name = "SERVICE_PROVIDER_CODE", length = 12)
	public String getServiceProviderCode() {
		return this.serviceProviderCode;
	}

	public void setServiceProviderCode(String serviceProviderCode) {
		this.serviceProviderCode = serviceProviderCode;
	}

	@Column(name = "PROVIDER_SESSION", length = 20)
	public String getProviderSession() {
		return this.providerSession;
	}

	public void setProviderSession(String providerSession) {
		this.providerSession = providerSession;
	}

	@Column(name = "TRANS_STATUS", length = 10)
	public String getTransStatus() {
		return this.transStatus;
	}

	public void setTransStatus(String transStatus) {
		this.transStatus = transStatus;
	}

	@Column(name = "TRANSID", length = 50)
	public String getTransid() {
		return this.transid;
	}

	public void setTransid(String transid) {
		this.transid = transid;
	}

	@Column(name = "AMOUNT", precision = 38, scale = 0)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "TRANS_DATE", length = 7)
	public Date getTransDate() {
		return this.transDate;
	}

	public void setTransDate(Date transDate) {
		this.transDate = transDate;
	}

	@Column(name = "TRANSID_REQUEST", length = 50)
	public String getTransidRequest() {
		return this.transidRequest;
	}

	public void setTransidRequest(String transidRequest) {
		this.transidRequest = transidRequest;
	}

	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "TELCO_STATUS", length = 20)
	public String getTelcoStatus() {
		return this.telcoStatus;
	}

	public void setTelcoStatus(String telcoStatus) {
		this.telcoStatus = telcoStatus;
	}

	@Column(name = "MESSAGE", length = 700)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "UPDATED_CHECK_TIME", length = 7)
	public Date getUpdatedCheckTime() {
		return this.updatedCheckTime;
	}

	public void setUpdatedCheckTime(Date updatedCheckTime) {
		this.updatedCheckTime = updatedCheckTime;
	}

	@Column(name = "TRANS_STATUS_OLD", length = 10)
	public String getTransStatusOld() {
		return this.transStatusOld;
	}

	public void setTransStatusOld(String transStatusOld) {
		this.transStatusOld = transStatusOld;
	}

	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "TOPUP_TYPE", precision = 38, scale = 0)
	public BigDecimal getTopupType() {
		return this.topupType;
	}

	public void setTopupType(BigDecimal topupType) {
		this.topupType = topupType;
	}

	@Column(name = "TELCO_TRANS_ID", length = 40)
	public String getTelcoTransId() {
		return this.telcoTransId;
	}

	public void setTelcoTransId(String telcoTransId) {
		this.telcoTransId = telcoTransId;
	}

	@Column(name = "SERVICE_PROVIDER_NAME", length = 50)
	public String getServiceProviderName() {
		return this.serviceProviderName;
	}

	public void setServiceProviderName(String serviceProviderName) {
		this.serviceProviderName = serviceProviderName;
	}

	@Column(name = "REC_ID", precision = 22, scale = 0)
	public BigDecimal getRecId() {
		return this.recId;
	}

	public void setRecId(BigDecimal recId) {
		this.recId = recId;
	}

	@Column(name = "STATUS_UPDATE", length = 10)
	public String getStatusUpdate() {
		return this.statusUpdate;
	}

	public void setStatusUpdate(String statusUpdate) {
		this.statusUpdate = statusUpdate;
	}

	@Column(name = "STATUS_UPDATE_TIME", length = 7)
	public Date getStatusUpdateTime() {
		return this.statusUpdateTime;
	}

	public void setStatusUpdateTime(Date statusUpdateTime) {
		this.statusUpdateTime = statusUpdateTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblTransactionsId))
			return false;
		TblTransactionsId castOther = (TblTransactionsId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
				&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getSessionid() == castOther.getSessionid()) || (this.getSessionid() != null
						&& castOther.getSessionid() != null && this.getSessionid().equals(castOther.getSessionid())))
				&& ((this.getPartnerCode() == castOther.getPartnerCode())
						|| (this.getPartnerCode() != null && castOther.getPartnerCode() != null
								&& this.getPartnerCode().equals(castOther.getPartnerCode())))
				&& ((this.getTargetAccount() == castOther.getTargetAccount())
						|| (this.getTargetAccount() != null && castOther.getTargetAccount() != null
								&& this.getTargetAccount().equals(castOther.getTargetAccount())))
				&& ((this.getServiceProviderCode() == castOther.getServiceProviderCode())
						|| (this.getServiceProviderCode() != null && castOther.getServiceProviderCode() != null
								&& this.getServiceProviderCode().equals(castOther.getServiceProviderCode())))
				&& ((this.getProviderSession() == castOther.getProviderSession())
						|| (this.getProviderSession() != null && castOther.getProviderSession() != null
								&& this.getProviderSession().equals(castOther.getProviderSession())))
				&& ((this.getTransStatus() == castOther.getTransStatus())
						|| (this.getTransStatus() != null && castOther.getTransStatus() != null
								&& this.getTransStatus().equals(castOther.getTransStatus())))
				&& ((this.getTransid() == castOther.getTransid()) || (this.getTransid() != null
						&& castOther.getTransid() != null && this.getTransid().equals(castOther.getTransid())))
				&& ((this.getAmount() == castOther.getAmount()) || (this.getAmount() != null
						&& castOther.getAmount() != null && this.getAmount().equals(castOther.getAmount())))
				&& ((this.getTransDate() == castOther.getTransDate()) || (this.getTransDate() != null
						&& castOther.getTransDate() != null && this.getTransDate().equals(castOther.getTransDate())))
				&& ((this.getTransidRequest() == castOther.getTransidRequest())
						|| (this.getTransidRequest() != null && castOther.getTransidRequest() != null
								&& this.getTransidRequest().equals(castOther.getTransidRequest())))
				&& ((this.getUpdatedDate() == castOther.getUpdatedDate())
						|| (this.getUpdatedDate() != null && castOther.getUpdatedDate() != null
								&& this.getUpdatedDate().equals(castOther.getUpdatedDate())))
				&& ((this.getTelcoStatus() == castOther.getTelcoStatus())
						|| (this.getTelcoStatus() != null && castOther.getTelcoStatus() != null
								&& this.getTelcoStatus().equals(castOther.getTelcoStatus())))
				&& ((this.getMessage() == castOther.getMessage()) || (this.getMessage() != null
						&& castOther.getMessage() != null && this.getMessage().equals(castOther.getMessage())))
				&& ((this.getUpdatedCheckTime() == castOther.getUpdatedCheckTime())
						|| (this.getUpdatedCheckTime() != null && castOther.getUpdatedCheckTime() != null
								&& this.getUpdatedCheckTime().equals(castOther.getUpdatedCheckTime())))
				&& ((this.getTransStatusOld() == castOther.getTransStatusOld())
						|| (this.getTransStatusOld() != null && castOther.getTransStatusOld() != null
								&& this.getTransStatusOld().equals(castOther.getTransStatusOld())))
				&& ((this.getCreatedDate() == castOther.getCreatedDate())
						|| (this.getCreatedDate() != null && castOther.getCreatedDate() != null
								&& this.getCreatedDate().equals(castOther.getCreatedDate())))
				&& ((this.getTopupType() == castOther.getTopupType()) || (this.getTopupType() != null
						&& castOther.getTopupType() != null && this.getTopupType().equals(castOther.getTopupType())))
				&& ((this.getTelcoTransId() == castOther.getTelcoTransId())
						|| (this.getTelcoTransId() != null && castOther.getTelcoTransId() != null
								&& this.getTelcoTransId().equals(castOther.getTelcoTransId())))
				&& ((this.getServiceProviderName() == castOther.getServiceProviderName())
						|| (this.getServiceProviderName() != null && castOther.getServiceProviderName() != null
								&& this.getServiceProviderName().equals(castOther.getServiceProviderName())))
				&& ((this.getRecId() == castOther.getRecId()) || (this.getRecId() != null
						&& castOther.getRecId() != null && this.getRecId().equals(castOther.getRecId())))
				&& ((this.getStatusUpdate() == castOther.getStatusUpdate())
						|| (this.getStatusUpdate() != null && castOther.getStatusUpdate() != null
								&& this.getStatusUpdate().equals(castOther.getStatusUpdate())))
				&& ((this.getStatusUpdateTime() == castOther.getStatusUpdateTime())
						|| (this.getStatusUpdateTime() != null && castOther.getStatusUpdateTime() != null
								&& this.getStatusUpdateTime().equals(castOther.getStatusUpdateTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getSessionid() == null ? 0 : this.getSessionid().hashCode());
		result = 37 * result + (getPartnerCode() == null ? 0 : this.getPartnerCode().hashCode());
		result = 37 * result + (getTargetAccount() == null ? 0 : this.getTargetAccount().hashCode());
		result = 37 * result + (getServiceProviderCode() == null ? 0 : this.getServiceProviderCode().hashCode());
		result = 37 * result + (getProviderSession() == null ? 0 : this.getProviderSession().hashCode());
		result = 37 * result + (getTransStatus() == null ? 0 : this.getTransStatus().hashCode());
		result = 37 * result + (getTransid() == null ? 0 : this.getTransid().hashCode());
		result = 37 * result + (getAmount() == null ? 0 : this.getAmount().hashCode());
		result = 37 * result + (getTransDate() == null ? 0 : this.getTransDate().hashCode());
		result = 37 * result + (getTransidRequest() == null ? 0 : this.getTransidRequest().hashCode());
		result = 37 * result + (getUpdatedDate() == null ? 0 : this.getUpdatedDate().hashCode());
		result = 37 * result + (getTelcoStatus() == null ? 0 : this.getTelcoStatus().hashCode());
		result = 37 * result + (getMessage() == null ? 0 : this.getMessage().hashCode());
		result = 37 * result + (getUpdatedCheckTime() == null ? 0 : this.getUpdatedCheckTime().hashCode());
		result = 37 * result + (getTransStatusOld() == null ? 0 : this.getTransStatusOld().hashCode());
		result = 37 * result + (getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode());
		result = 37 * result + (getTopupType() == null ? 0 : this.getTopupType().hashCode());
		result = 37 * result + (getTelcoTransId() == null ? 0 : this.getTelcoTransId().hashCode());
		result = 37 * result + (getServiceProviderName() == null ? 0 : this.getServiceProviderName().hashCode());
		result = 37 * result + (getRecId() == null ? 0 : this.getRecId().hashCode());
		result = 37 * result + (getStatusUpdate() == null ? 0 : this.getStatusUpdate().hashCode());
		result = 37 * result + (getStatusUpdateTime() == null ? 0 : this.getStatusUpdateTime().hashCode());
		return result;
	}

}
