// default package
// Generated May 28, 2020 11:10:15 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblTransactions generated by hbm2java
 */
@Entity
@Table(name = "TBL_TRANSACTIONS")
public class TblTransactions implements java.io.Serializable {

	private TblTransactionsId id;

	public TblTransactions() {
	}

	public TblTransactions(TblTransactionsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "username", column = @Column(name = "USERNAME", length = 10)),
			@AttributeOverride(name = "sessionid", column = @Column(name = "SESSIONID", length = 100)),
			@AttributeOverride(name = "partnerCode", column = @Column(name = "PARTNER_CODE", length = 10)),
			@AttributeOverride(name = "targetAccount", column = @Column(name = "TARGET_ACCOUNT", length = 50)),
			@AttributeOverride(name = "serviceProviderCode", column = @Column(name = "SERVICE_PROVIDER_CODE", length = 12)),
			@AttributeOverride(name = "providerSession", column = @Column(name = "PROVIDER_SESSION", length = 20)),
			@AttributeOverride(name = "transStatus", column = @Column(name = "TRANS_STATUS", length = 10)),
			@AttributeOverride(name = "transid", column = @Column(name = "TRANSID", length = 50)),
			@AttributeOverride(name = "amount", column = @Column(name = "AMOUNT", precision = 38, scale = 0)),
			@AttributeOverride(name = "transDate", column = @Column(name = "TRANS_DATE", length = 7)),
			@AttributeOverride(name = "transidRequest", column = @Column(name = "TRANSID_REQUEST", length = 50)),
			@AttributeOverride(name = "updatedDate", column = @Column(name = "UPDATED_DATE", length = 7)),
			@AttributeOverride(name = "telcoStatus", column = @Column(name = "TELCO_STATUS", length = 20)),
			@AttributeOverride(name = "message", column = @Column(name = "MESSAGE", length = 700)),
			@AttributeOverride(name = "updatedCheckTime", column = @Column(name = "UPDATED_CHECK_TIME", length = 7)),
			@AttributeOverride(name = "transStatusOld", column = @Column(name = "TRANS_STATUS_OLD", length = 10)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CREATED_DATE", length = 7)),
			@AttributeOverride(name = "topupType", column = @Column(name = "TOPUP_TYPE", precision = 38, scale = 0)),
			@AttributeOverride(name = "telcoTransId", column = @Column(name = "TELCO_TRANS_ID", length = 40)),
			@AttributeOverride(name = "serviceProviderName", column = @Column(name = "SERVICE_PROVIDER_NAME", length = 50)),
			@AttributeOverride(name = "recId", column = @Column(name = "REC_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "statusUpdate", column = @Column(name = "STATUS_UPDATE", length = 10)),
			@AttributeOverride(name = "statusUpdateTime", column = @Column(name = "STATUS_UPDATE_TIME", length = 7)) })
	public TblTransactionsId getId() {
		return this.id;
	}

	public void setId(TblTransactionsId id) {
		this.id = id;
	}

}
