package springboot.hbn.entities;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblBrand generated by hbm2java
 */
@Entity
@Table(name = "tbl_brand")
public class TblBrand implements java.io.Serializable {

	private String brand_id;
	private String branch_name;
	private String branch_code;
//	private String created_date;

	public TblBrand() {
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "brand_id", unique = true, nullable = false)
	public String getBrandId() {
		return this.brand_id;
	}

	public void setBrandId(String brandId) {
		this.brand_id = brandId;
	}

	@Column(name = "branch_name", nullable = false, length = 50)
	public String getBranchName() {
		return this.branch_name;
	}

	public void setBranchName(String branchName) {
		this.branch_name = branchName;
	}

	@Column(name = "branch_code", nullable = false, length = 50)
	public String getBranchCode() {
		return this.branch_code;
	}

	public void setBranchCode(String branchCode) {
		this.branch_code = branchCode;
	}

	
//	@Column(name = "created_date", nullable = false, length = 19)
//	public String getCreatedDate() {
//		return this.created_date;
//	}
//
//	public void setCreatedDate(String createdDate) {
//		this.created_date = createdDate;
//	}

}
