package springboot.hbn.entities;

// default package
// Generated Aug 20, 2021, 10:41:14 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;



/**
 * TblBranchBank generated by hbm2java
 */
@Entity
@Table(name = "tbl_branch_bank")
public class TblBranchBank implements java.io.Serializable {

	private Integer rowId;
	private String bankAccount;
	private int ordinal;
	private int status;
	private int branchId;
	private int bankId;
	private String bankAccName;
	private String bankBranch;
	
//	@OneToOne(targetEntity = TblBanks.class, cascade = CascadeType.ALL)
//    @JoinColumn(name = "row_id")
//    private TblBanks tblBanks;
//	
//	
//	
//	public TblBanks getTblBanks() {
//		return tblBanks;
//	}
//
//	public void setTblBanks(TblBanks tblBanks) {
//		this.tblBanks = tblBanks;
//	}

	public TblBranchBank() {
	}

	public TblBranchBank(String bankAccount, int ordinal, int status, int branchId, int bankId) {
		this.bankAccount = bankAccount;
		this.ordinal = ordinal;
		this.status = status;
		this.branchId = branchId;
		this.bankId = bankId;
	}

	public TblBranchBank(String bankAccount, int ordinal, int status, int branchId, int bankId, String bankAccName,
			String bankBranch) {
		this.bankAccount = bankAccount;
		this.ordinal = ordinal;
		this.status = status;
		this.branchId = branchId;
		this.bankId = bankId;
		this.bankAccName = bankAccName;
		this.bankBranch = bankBranch;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@Column(name = "bank_account", nullable = false, length = 20)
	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	@Column(name = "ordinal", nullable = false)
	public int getOrdinal() {
		return this.ordinal;
	}

	public void setOrdinal(int ordinal) {
		this.ordinal = ordinal;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "branch_id", nullable = false)
	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	@Column(name = "bank_id", nullable = false)
	public int getBankId() {
		return this.bankId;
	}

	public void setBankId(int bankId) {
		this.bankId = bankId;
	}

	@Column(name = "bank_acc_name")
	public String getBankAccName() {
		return this.bankAccName;
	}

	public void setBankAccName(String bankAccName) {
		this.bankAccName = bankAccName;
	}

	@Column(name = "bank_branch")
	public String getBankBranch() {
		return this.bankBranch;
	}

	public void setBankBranch(String bankBranch) {
		this.bankBranch = bankBranch;
	}

}
