package springboot.hbn.entities;

// default package
// Generated May 30, 2021, 10:38:44 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblBlackList generated by hbm2java
 */
@Entity
@Table(name = "tbl_black_list")
public class TblBlackList implements java.io.Serializable {

	private Integer black_list_id;
	private int borrower_id;
	private Date escape_date;
	private Integer entry_status;
	private Date join_date;
	private int group_debt_id;
	private Date effective_date_from;
	private Date effective_date_to;
	private String borrower_name;
	private String borrower_id_number;

	public TblBlackList() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "black_list_id", unique = true, nullable = false)
	public Integer getBlackListId() {
		return this.black_list_id;
	}

	public void setBlackListId(Integer blackListId) {
		this.black_list_id = blackListId;
	}

	@Column(name = "borrower_id", nullable = false)
	public int getBorrowerId() {
		return this.borrower_id;
	}

	public void setBorrowerId(int borrowerId) {
		this.borrower_id = borrowerId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "escape_date", nullable = false, length = 19)
	public Date getEscapeDate() {
		return this.escape_date;
	}

	public void setEscapeDate(Date escapeDate) {
		this.escape_date = escapeDate;
	}

	@Column(name = "entry_status")
	public Integer getEntryStatus() {
		return this.entry_status;
	}

	public void setEntryStatus(Integer entryStatus) {
		this.entry_status = entryStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "join_date", nullable = false, length = 19)
	public Date getJoinDate() {
		return this.join_date;
	}

	public void setJoinDate(Date joinDate) {
		this.join_date = joinDate;
	}

	@Column(name = "group_debt_id", nullable = false)
	public int getGroupDebtId() {
		return this.group_debt_id;
	}

	public void setGroupDebtId(int groupDebtId) {
		this.group_debt_id = groupDebtId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "effective_date_from", nullable = false, length = 10)
	public Date getEffectiveDateFrom() {
		return this.effective_date_from;
	}

	public void setEffectiveDateFrom(Date effectiveDateFrom) {
		this.effective_date_from = effectiveDateFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "effective_date_to", nullable = false, length = 10)
	public Date getEffectiveDateTo() {
		return this.effective_date_to;
	}

	public void setEffectiveDateTo(Date effectiveDateTo) {
		this.effective_date_to = effectiveDateTo;
	}

	@Column(name = "borrower_name", nullable = false, length = 100)
	public String getBorrowerName() {
		return this.borrower_name;
	}

	public void setBorrowerName(String borrowerName) {
		this.borrower_name = borrowerName;
	}

	@Column(name = "borrower_id_number", nullable = false, length = 50)
	public String getBorrowerIdNumber() {
		return this.borrower_id_number;
	}

	public void setBorrowerIdNumber(String borrowerIdNumber) {
		this.borrower_id_number = borrowerIdNumber;
	}

}
