package springboot.hbn.entities;

// default package
// Generated Jun 1, 2021, 12:37:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Id;
import javax.persistence.Table;

import springboot.hbn.home.TblBorrowerHome;
import springboot.utils.GsonUltilities;

/**
 * TblBanks generated by hbm2java
 */
@Entity
@Table(name = "tbl_banks")
public class TblBanks implements java.io.Serializable {

	private String row_id;
	private String bank_name;
	private String bank_code;
	private String status;
	private String banh_sort_name;
	private String bank_support_function;

	public TblBanks() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "row_id", unique = true, nullable = false)
	public String getRowId() {
		return this.row_id;
	}

	public void setRowId(String rowId) {
		this.row_id = rowId;
	}

	@Column(name = "bank_name", nullable = false, length = 200)
	public String getBankName() {
		return this.bank_name;
	}

	public void setBankName(String bankName) {
		this.bank_name = bankName;
	}

	@Column(name = "bank_code", nullable = false, length = 50)
	public String getBankCode() {
		return this.bank_code;
	}

	public void setBankCode(String bankCode) {
		this.bank_code = bankCode;
	}

	@Column(name = "status", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "banh_sort_name", nullable = false, length = 100)
	public String getBanhSortName() {
		return this.banh_sort_name;
	}

	public void setBanhSortName(String banhSortName) {
		this.banh_sort_name = banhSortName;
	}

	@Column(name = "bank_support_function")
	public String getBankSupportFunction() {
		return this.bank_support_function;
	}

	public void setBankSupportFunction(String bankSupportFunction) {
		this.bank_support_function = bankSupportFunction;
	}

	public static void main(String[] args) {
		try {
			List<Object> lstObj = new TblBorrowerHome().listAllObject(new TblProduct2());
			System.out.println(lstObj.size());
			for (Object object : lstObj) {
				System.out.println(GsonUltilities.toJson(object));
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
