package springboot.hbn.entities;

// default package
// Generated May 29, 2021, 3:10:44 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblExtraFee generated by hbm2java
 */
@Entity
@Table(name = "tbl_extra_fee")
public class TblExtraFee2 implements java.io.Serializable {

	private String extra_fee_id;
	private String extra_fee_name;
	private String extra_fee_code;
	private String created_by;
	private String fix_fee_amount;
	private String fix_fee_percent;
	private String created_date;
	private String fee_type;
	private String pay_type;

	public TblExtraFee2() {
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "extra_fee_id", unique = true, nullable = false)
	public String getExtraFeeId() {
		return this.extra_fee_id;
	}

	public void setExtraFeeId(String extraFeeId) {
		this.extra_fee_id = extraFeeId;
	}

	@Column(name = "extra_fee_name", nullable = false, length = 50)
	public String getExtraFeeName() {
		return this.extra_fee_name;
	}

	public void setExtraFeeName(String extraFeeName) {
		this.extra_fee_name = extraFeeName;
	}

	@Column(name = "extra_fee_code", nullable = false, length = 50)
	public String getExtraFeeCode() {
		return this.extra_fee_code;
	}

	public void setExtraFeeCode(String extraFeeCode) {
		this.extra_fee_code = extraFeeCode;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.created_by;
	}

	public void setCreatedBy(String createdBy) {
		this.created_by = createdBy;
	}

	@Column(name = "fix_fee_amount", precision = 10, scale = 0)
	public String getFixFeeAmount() {
		return this.fix_fee_amount;
	}

	public void setFixFeeAmount(String fixFeeAmount) {
		this.fix_fee_amount = fixFeeAmount;
	}

	@Column(name = "fix_fee_percent", precision = 22, scale = 0)
	public String getFixFeePercent() {
		return this.fix_fee_percent;
	}

	public void setFixFeePercent(String fixFeePercent) {
		this.fix_fee_percent = fixFeePercent;
	}

//	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public String getCreatedDate() {
		return this.created_date;
	}

	public void setCreatedDate(String createdDate) {
		this.created_date = createdDate;
	}

	@Column(name = "fee_type", nullable = false)
	public String getFeeType() {
		return this.fee_type;
	}

	public void setFeeType(String feeType) {
		this.fee_type = feeType;
	}

	@Column(name = "pay_type")
	public String getPayType() {
		return this.pay_type;
	}

	public void setPayType(String payType) {
		this.pay_type = payType;
	}

}
