package springboot.hbn.entities;

// default package
// Generated May 29, 2021, 3:10:44 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblExtraFee generated by hbm2java
 */
@Entity
@Table(name = "tbl_extra_fee")
public class TblExtraFee implements java.io.Serializable {

	private Integer extra_fee_id;
	private String extra_fee_name;
	private String extra_fee_code;
	private String created_by;
	private Long fix_fee_amount;
	private Double fix_fee_percent;
	private Date created_date;
	private int fee_type;
	private Integer pay_type;

	public TblExtraFee() {
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "extra_fee_id", unique = true, nullable = false)
	public Integer getExtraFeeId() {
		return this.extra_fee_id;
	}

	public void setExtraFeeId(Integer extraFeeId) {
		this.extra_fee_id = extraFeeId;
	}

	@Column(name = "extra_fee_name", nullable = false, length = 50)
	public String getExtraFeeName() {
		return this.extra_fee_name;
	}

	public void setExtraFeeName(String extraFeeName) {
		this.extra_fee_name = extraFeeName;
	}

	@Column(name = "extra_fee_code", nullable = false, length = 50)
	public String getExtraFeeCode() {
		return this.extra_fee_code;
	}

	public void setExtraFeeCode(String extraFeeCode) {
		this.extra_fee_code = extraFeeCode;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.created_by;
	}

	public void setCreatedBy(String createdBy) {
		this.created_by = createdBy;
	}

	@Column(name = "fix_fee_amount", precision = 10, scale = 0)
	public Long getFixFeeAmount() {
		return this.fix_fee_amount;
	}

	public void setFixFeeAmount(Long fixFeeAmount) {
		this.fix_fee_amount = fixFeeAmount;
	}

	@Column(name = "fix_fee_percent", precision = 22, scale = 0)
	public Double getFixFeePercent() {
		return this.fix_fee_percent;
	}

	public void setFixFeePercent(Double fixFeePercent) {
		this.fix_fee_percent = fixFeePercent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.created_date;
	}

	public void setCreatedDate(Date createdDate) {
		this.created_date = createdDate;
	}

	@Column(name = "fee_type", nullable = false)
	public int getFeeType() {
		return this.fee_type;
	}

	public void setFeeType(int feeType) {
		this.fee_type = feeType;
	}

	@Column(name = "pay_type")
	public Integer getPayType() {
		return this.pay_type;
	}

	public void setPayType(Integer payType) {
		this.pay_type = payType;
	}

}
