package springboot.hbn.entities;

// default package
// Generated Aug 10, 2021, 10:14:44 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblInsuranceProvidersApi generated by hbm2java
 */
@Entity
@Table(name = "tbl_insurance_providers_api")
public class TblInsuranceProvidersApi implements java.io.Serializable {

	private Long insurance_provider_id;
	private String insurance_code;
	private String insurance_name;
	private Integer active_stt;
//	private Date createdDate;
//	private Date editedDate;
	private Integer fix_fee;
	private Float fix_rate;
	private String insurance_api;
	private String auth_token;
	private String api_acc;
	private String api_pass;
	private String auth_token_expires;
	private Integer insurance_default;
	private Integer include_vat_fee;
	private Integer include_interest;
	private String bank_message_transfer;
	private String bank_message_eg;
	private String hotline;

	public TblInsuranceProvidersApi() {
	}

	public TblInsuranceProvidersApi(String insuranceCode, String insuranceName, Integer activeStt, Date createdDate,
			Date editedDate, Integer fixFee, Float fixRate, String insuranceApi, String authToken, String apiAcc,
			String apiPass, String authTokenExpires, Integer insuranceDefault, Integer includeVatFee,
			Integer includeInterest, String bankMessageTransfer, String bankMessageEg, String hotline) {
		this.insurance_code = insuranceCode;
		this.insurance_name = insuranceName;
		this.active_stt = activeStt;
//		this.createdDate = createdDate;
//		this.editedDate = editedDate;
		this.fix_fee = fixFee;
		this.fix_rate = fixRate;
		this.insurance_api = insuranceApi;
		this.auth_token = authToken;
		this.api_acc = apiAcc;
		this.api_pass = apiPass;
		this.auth_token_expires = authTokenExpires;
		this.insurance_default = insuranceDefault;
		this.include_vat_fee = includeVatFee;
		this.include_interest = includeInterest;
		this.bank_message_transfer = bankMessageTransfer;
		this.bank_message_eg = bankMessageEg;
		this.hotline = hotline;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "insurance_provider_id", unique = true, nullable = false)
	public Long getInsuranceProviderId() {
		return this.insurance_provider_id;
	}

	public void setInsuranceProviderId(Long insuranceProviderId) {
		this.insurance_provider_id = insuranceProviderId;
	}

	@Column(name = "insurance_code")
	public String getInsuranceCode() {
		return this.insurance_code;
	}

	public void setInsuranceCode(String insuranceCode) {
		this.insurance_code = insuranceCode;
	}

	@Column(name = "insurance_name")
	public String getInsuranceName() {
		return this.insurance_name;
	}

	public void setInsuranceName(String insuranceName) {
		this.insurance_name = insuranceName;
	}

	@Column(name = "active_stt")
	public Integer getActiveStt() {
		return this.active_stt;
	}

	public void setActiveStt(Integer activeStt) {
		this.active_stt = activeStt;
	}

	

	@Column(name = "fix_fee")
	public Integer getFixFee() {
		return this.fix_fee;
	}

	public void setFixFee(Integer fixFee) {
		this.fix_fee = fixFee;
	}

	@Column(name = "fix_rate", precision = 12, scale = 0)
	public Float getFixRate() {
		return this.fix_rate;
	}

	public void setFixRate(Float fixRate) {
		this.fix_rate = fixRate;
	}

	@Column(name = "insurance_api")
	public String getInsuranceApi() {
		return this.insurance_api;
	}

	public void setInsuranceApi(String insuranceApi) {
		this.insurance_api = insuranceApi;
	}

	@Column(name = "auth_token", length = 2000)
	public String getAuthToken() {
		return this.auth_token;
	}

	public void setAuthToken(String authToken) {
		this.auth_token = authToken;
	}

	@Column(name = "api_acc")
	public String getApiAcc() {
		return this.api_acc;
	}

	public void setApiAcc(String apiAcc) {
		this.api_acc = apiAcc;
	}

	@Column(name = "api_pass")
	public String getApiPass() {
		return this.api_pass;
	}

	public void setApiPass(String apiPass) {
		this.api_pass = apiPass;
	}

	@Column(name = "auth_token_expires")
	public String getAuthTokenExpires() {
		return this.auth_token_expires;
	}

	public void setAuthTokenExpires(String authTokenExpires) {
		this.auth_token_expires = authTokenExpires;
	}

	@Column(name = "insurance_default")
	public Integer getInsuranceDefault() {
		return this.insurance_default;
	}

	public void setInsuranceDefault(Integer insuranceDefault) {
		this.insurance_default = insuranceDefault;
	}

	@Column(name = "include_vat_fee")
	public Integer getIncludeVatFee() {
		return this.include_vat_fee;
	}

	public void setIncludeVatFee(Integer includeVatFee) {
		this.include_vat_fee = includeVatFee;
	}

	@Column(name = "include_interest")
	public Integer getIncludeInterest() {
		return this.include_interest;
	}

	public void setIncludeInterest(Integer includeInterest) {
		this.include_interest = includeInterest;
	}

	@Column(name = "bank_message_transfer", length = 500)
	public String getBankMessageTransfer() {
		return this.bank_message_transfer;
	}

	public void setBankMessageTransfer(String bankMessageTransfer) {
		this.bank_message_transfer = bankMessageTransfer;
	}

	@Column(name = "bank_message_eg", length = 500)
	public String getBankMessageEg() {
		return this.bank_message_eg;
	}

	public void setBankMessageEg(String bankMessageEg) {
		this.bank_message_eg = bankMessageEg;
	}

	@Column(name = "hotline", length = 20)
	public String getHotline() {
		return this.hotline;
	}

	public void setHotline(String hotline) {
		this.hotline = hotline;
	}

}
