package springboot.hbn.entities;

// default package
// Generated Jul 11, 2021, 2:58:25 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblInsuranceFeeApi generated by hbm2java
 */
@Entity
@Table(name = "tbl_insurance_fee_api")
public class TblInsuranceFeeApi implements java.io.Serializable {

	private Integer fee_id;
	private Integer from_number_of_months;
	private Integer to_number_of_months;
	private Integer fix_fee;
	private Float rate_fee;
	private Integer apply_from_date;
	private Integer apply_to_date;
	private Integer group_id;

	public TblInsuranceFeeApi() {
	}

	public TblInsuranceFeeApi(Integer fromNumberOfMonths, Integer toNumberOfMonths, Integer fixFee, Float rateFee,
			Integer applyFromDate, Integer applyToDate, Integer groupId) {
		this.from_number_of_months = fromNumberOfMonths;
		this.to_number_of_months = toNumberOfMonths;
		this.fix_fee = fixFee;
		this.rate_fee = rateFee;
		this.apply_from_date = applyFromDate;
		this.apply_to_date = applyToDate;
		this.group_id = groupId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "fee_id", unique = true, nullable = false)
	public Integer getFeeId() {
		return this.fee_id;
	}

	public void setFeeId(Integer feeId) {
		this.fee_id = feeId;
	}

	@Column(name = "from_number_of_months")
	public Integer getFromNumberOfMonths() {
		return this.from_number_of_months;
	}

	public void setFromNumberOfMonths(Integer fromNumberOfMonths) {
		this.from_number_of_months = fromNumberOfMonths;
	}

	@Column(name = "to_number_of_months")
	public Integer getToNumberOfMonths() {
		return this.to_number_of_months;
	}

	public void setToNumberOfMonths(Integer toNumberOfMonths) {
		this.to_number_of_months = toNumberOfMonths;
	}

	@Column(name = "fix_fee")
	public Integer getFixFee() {
		return this.fix_fee;
	}

	public void setFixFee(Integer fixFee) {
		this.fix_fee = fixFee;
	}

	@Column(name = "rate_fee", precision = 12, scale = 0)
	public Float getRateFee() {
		return this.rate_fee;
	}

	public void setRateFee(Float rateFee) {
		this.rate_fee = rateFee;
	}

	@Column(name = "apply_from_date")
	public Integer getApplyFromDate() {
		return this.apply_from_date;
	}

	public void setApplyFromDate(Integer applyFromDate) {
		this.apply_from_date = applyFromDate;
	}

	@Column(name = "apply_to_date")
	public Integer getApplyToDate() {
		return this.apply_to_date;
	}

	public void setApplyToDate(Integer applyToDate) {
		this.apply_to_date = applyToDate;
	}

	@Column(name = "group_id")
	public Integer getGroupId() {
		return this.group_id;
	}

	public void setGroupId(Integer groupId) {
		this.group_id = groupId;
	}

}
