package springboot.hbn.entities;// default package
// Generated May 21, 2021, 12:14:22 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblProvincesId generated by hbm2java
 */
@Embeddable
public class TblProvincesId implements java.io.Serializable {

	private String provinceCode;
	private String provinceName;

	public TblProvincesId() {
	}

	public TblProvincesId(String provinceCode, String provinceName) {
		this.provinceCode = provinceCode;
		this.provinceName = provinceName;
	}

	@Column(name = "province_code", nullable = false, length = 10)
	public String getProvinceCode() {
		return this.provinceCode;
	}

	public void setProvinceCode(String provinceCode) {
		this.provinceCode = provinceCode;
	}

	@Column(name = "province_name", nullable = false, length = 100)
	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblProvincesId))
			return false;
		TblProvincesId castOther = (TblProvincesId) other;

		return ((this.getProvinceCode() == castOther.getProvinceCode()) || (this.getProvinceCode() != null
				&& castOther.getProvinceCode() != null && this.getProvinceCode().equals(castOther.getProvinceCode())))
				&& ((this.getProvinceName() == castOther.getProvinceName())
						|| (this.getProvinceName() != null && castOther.getProvinceName() != null
								&& this.getProvinceName().equals(castOther.getProvinceName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProvinceCode() == null ? 0 : this.getProvinceCode().hashCode());
		result = 37 * result + (getProvinceName() == null ? 0 : this.getProvinceName().hashCode());
		return result;
	}

}
