package springboot.hbn.entities;

// default package
// Generated May 29, 2021, 3:10:44 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblProvinces generated by hbm2java
 */
@Entity
@Table(name = "tbl_provinces", catalog = "db_fintech")
public class TblProvinces implements java.io.Serializable {

	private TblProvincesId id;

	public TblProvinces() {
	}

	public TblProvinces(TblProvincesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "provinceCode", column = @Column(name = "province_code", nullable = false, length = 10)),
			@AttributeOverride(name = "provinceName", column = @Column(name = "province_name", nullable = false, length = 100)) })
	public TblProvincesId getId() {
		return this.id;
	}

	public void setId(TblProvincesId id) {
		this.id = id;
	}

}
