package springboot.hbn.entities;

// default package
// Generated May 29, 2021, 3:19:16 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblRateConfig generated by hbm2java
 */
@Entity
@Table(name = "tbl_rate_config")
public class TblRateConfig implements java.io.Serializable {

	private Integer rate_id;
	private String rate_name;
	private String rate_code;
	private int rate_type;
	private float rate_value;
	private Integer active_status;

	public TblRateConfig() {
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rate_id", unique = true, nullable = false)
	public Integer getRateId() {
		return this.rate_id;
	}

	public void setRateId(Integer rateId) {
		this.rate_id = rateId;
	}

	@Column(name = "rate_name", nullable = false)
	public String getRateName() {
		return this.rate_name;
	}

	public void setRateName(String rateName) {
		this.rate_name = rateName;
	}

	@Column(name = "rate_code", nullable = false)
	public String getRateCode() {
		return this.rate_code;
	}

	public void setRateCode(String rateCode) {
		this.rate_code = rateCode;
	}

	@Column(name = "rate_type", nullable = false)
	public int getRateType() {
		return this.rate_type;
	}

	public void setRateType(int rateType) {
		this.rate_type = rateType;
	}

	@Column(name = "rate_value", nullable = false, precision = 12, scale = 0)
	public float getRateValue() {
		return this.rate_value;
	}

	public void setRateValue(float rateValue) {
		this.rate_value = rateValue;
	}

	@Column(name = "active_status")
	public Integer getActiveStatus() {
		return this.active_status;
	}

	public void setActiveStatus(Integer activeStatus) {
		this.active_status = activeStatus;
	}

}
