package springboot.hbn.entities;

// default package
// Generated May 29, 2021, 3:19:16 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblSystemConfigurations generated by hbm2java
 */
@Entity
@Table(name = "tbl_system_configurations")
public class TblSystemConfigurations implements java.io.Serializable {

	private int config_id;
	private String config_name;
	private Float config_value;
	private Integer status;
	private Integer config_type;

	public TblSystemConfigurations() {
	}

	

	@Id

	@Column(name = "config_id", unique = true, nullable = false)
	public int getConfigId() {
		return this.config_id;
	}

	public void setConfigId(int configId) {
		this.config_id = configId;
	}

	@Column(name = "config_name", nullable = false)
	public String getConfigName() {
		return this.config_name;
	}

	public void setConfigName(String configName) {
		this.config_name = configName;
	}

	@Column(name = "config_value", precision = 8, scale = 0)
	public Float getConfigValue() {
		return this.config_value;
	}

	public void setConfigValue(Float configValue) {
		this.config_value = configValue;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "config_type")
	public Integer getConfigType() {
		return this.config_type;
	}

	public void setConfigType(Integer configType) {
		this.config_type = configType;
	}

}
