package springboot.hbn.entities;

import java.text.Normalizer;

// default package
// Generated May 29, 2021, 3:19:16 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.List;
import java.util.regex.Pattern;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.http.converter.json.GsonBuilderUtils;

import springboot.hbn.home.TblSponsorHome;
import springboot.utils.GsonUltilities;

/**
 * TblSponsor generated by hbm2java
 */
@Entity
@Table(name = "tbl_sponsor")
public class TblSponsor implements java.io.Serializable {

	private Integer sponsor_id;
	private String sponsor_name;
	private String sponsor_en_name;
	private Integer total_disbursement;
	private Integer total_settlement;

	@Column(name = "total_disbursement", nullable = true)
	public Integer getTotal_disbursement() {
		return total_disbursement;
	}

	public void setTotal_disbursement(Integer total_disbursement) {
		this.total_disbursement = total_disbursement;
	}

	@Column(name = "total_settlement", nullable = true)
	public Integer getTotal_settlement() {
		return total_settlement;
	}

	public void setTotal_settlement(Integer total_settlement) {
		this.total_settlement = total_settlement;
	}

	@Column(name = "sponsor_en_name", nullable = false, length = 100)
	public String getSponsor_en_name() {
		return sponsor_en_name;
	}

	public static String deAccent(String str) {
		String nfdNormalizedString = Normalizer.normalize(str, Normalizer.Form.NFD);
		Pattern pattern = Pattern.compile("\\p{InCombiningDiacriticalMarks}+");
		return pattern.matcher(nfdNormalizedString).replaceAll("").replace("đ", "d").replace("Đ", "D");
	}

	public void setSponsor_en_name(String sponsor_en_name) {
		this.sponsor_en_name = sponsor_en_name;
	}

	private String sponsor_mobile;
	private int sponsor_status;
//	private Date deactive_date;
	private String description;
//	private Date created_date;
	private String sponsor_mobile2;
	private String sponsor_address;
	private String sponsor_email;
	private String sponsor_id_number;
	private String sponsor_id_issued_by;
//	private Date sponsor_id_issued_date;
	private int sponsor_account_id;
	private String sponsor_province_name;
	private String sponsor_bank_account;
	private String sponsor_bank_name;
	private String sponsor_bank_branch;
	private String sponsor_investment_commitment;
	private int sponsor_type;
	private int sponsor_investment_type;
	private String sponsor_code;

	public TblSponsor() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sponsor_id", unique = true, nullable = false)
	public Integer getSponsorId() {
		return this.sponsor_id;
	}

	public void setSponsorId(Integer sponsorId) {
		this.sponsor_id = sponsorId;
	}

	@Column(name = "sponsor_name", nullable = false, length = 100)
	public String getSponsorName() {
		return this.sponsor_name;
	}

	public void setSponsorName(String sponsorName) {
		this.sponsor_name = sponsorName;
	}

	@Column(name = "sponsor_mobile", nullable = false, length = 20)
	public String getSponsorMobile() {
		return this.sponsor_mobile;
	}

	public void setSponsorMobile(String sponsorMobile) {
		this.sponsor_mobile = sponsorMobile;
	}

	@Column(name = "sponsor_status", nullable = false)
	public int getSponsorStatus() {
		return this.sponsor_status;
	}

	public void setSponsorStatus(int sponsorStatus) {
		this.sponsor_status = sponsorStatus;
	}

//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "deactive_date", nullable = false, length = 19)
//	public Date getDeactiveDate() {
//		return this.deactive_date;
//	}
//
//	public void setDeactiveDate(Date deactiveDate) {
//		this.deactive_date = deactiveDate;
//	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "created_date", nullable = false, length = 19)
//	public Date getCreatedDate() {
//		return this.created_date;
//	}
//
//	public void setCreatedDate(Date createdDate) {
//		this.created_date = createdDate;
//	}

	@Column(name = "sponsor_mobile_2", nullable = false, length = 15)
	public String getSponsorMobile2() {
		return this.sponsor_mobile2;
	}

	public void setSponsorMobile2(String sponsorMobile2) {
		this.sponsor_mobile2 = sponsorMobile2;
	}

	@Column(name = "sponsor_address", nullable = false, length = 200)
	public String getSponsorAddress() {
		return this.sponsor_address;
	}

	public void setSponsorAddress(String sponsorAddress) {
		this.sponsor_address = sponsorAddress;
	}

	@Column(name = "sponsor_email", nullable = false, length = 200)
	public String getSponsorEmail() {
		return this.sponsor_email;
	}

	public void setSponsorEmail(String sponsorEmail) {
		this.sponsor_email = sponsorEmail;
	}

	@Column(name = "sponsor_id_number", nullable = false, length = 20)
	public String getSponsorIdNumber() {
		return this.sponsor_id_number;
	}

	public void setSponsorIdNumber(String sponsorIdNumber) {
		this.sponsor_id_number = sponsorIdNumber;
	}

	@Column(name = "sponsor_id_issued_by", nullable = false, length = 200)
	public String getSponsorIdIssuedBy() {
		return this.sponsor_id_issued_by;
	}

	public void setSponsorIdIssuedBy(String sponsorIdIssuedBy) {
		this.sponsor_id_issued_by = sponsorIdIssuedBy;
	}

//	@Temporal(TemporalType.DATE)
//	@Column(name = "sponsor_id_issued_date", nullable = false, length = 10)
//	public Date getSponsorIdIssuedDate() {
//		return this.sponsor_id_issued_date;
//	}
//
//	public void setSponsorIdIssuedDate(Date sponsorIdIssuedDate) {
//		this.sponsor_id_issued_date = sponsorIdIssuedDate;
//	}

	@Column(name = "sponsor_account_id", nullable = false)
	public int getSponsorAccountId() {
		return this.sponsor_account_id;
	}

	public void setSponsorAccountId(int sponsorAccountId) {
		this.sponsor_account_id = sponsorAccountId;
	}

	@Column(name = "sponsor_province_name", nullable = false, length = 100)
	public String getSponsorProvinceName() {
		return this.sponsor_province_name;
	}

	public void setSponsorProvinceName(String sponsorProvinceName) {
		this.sponsor_province_name = sponsorProvinceName;
	}

	@Column(name = "sponsor_bank_account", nullable = false, length = 100)
	public String getSponsorBankAccount() {
		return this.sponsor_bank_account;
	}

	public void setSponsorBankAccount(String sponsorBankAccount) {
		this.sponsor_bank_account = sponsorBankAccount;
	}

	@Column(name = "sponsor_bank_name", nullable = false, length = 100)
	public String getSponsorBankName() {
		return this.sponsor_bank_name;
	}

	public void setSponsorBankName(String sponsorBankName) {
		this.sponsor_bank_name = sponsorBankName;
	}

	@Column(name = "sponsor_bank_branch", nullable = false, length = 100)
	public String getSponsorBankBranch() {
		return this.sponsor_bank_branch;
	}

	public void setSponsorBankBranch(String sponsorBankBranch) {
		this.sponsor_bank_branch = sponsorBankBranch;
	}

	@Column(name = "sponsor_investment_commitment", nullable = false, length = 100)
	public String getSponsorInvestmentCommitment() {
		return this.sponsor_investment_commitment;
	}

	public void setSponsorInvestmentCommitment(String sponsorInvestmentCommitment) {
		this.sponsor_investment_commitment = sponsorInvestmentCommitment;
	}

	@Column(name = "sponsor_type", nullable = false)
	public int getSponsorType() {
		return this.sponsor_type;
	}

	public void setSponsorType(int sponsorType) {
		this.sponsor_type = sponsorType;
	}

	@Column(name = "sponsor_investment_type", nullable = false)
	public int getSponsorInvestmentType() {
		return this.sponsor_investment_type;
	}

	public void setSponsorInvestmentType(int sponsorInvestmentType) {
		this.sponsor_investment_type = sponsorInvestmentType;
	}

	@Column(name = "sponsor_code", nullable = false, length = 50)
	public String getSponsorCode() {
		return this.sponsor_code;
	}

	public void setSponsorCode(String sponsorCode) {
		this.sponsor_code = sponsorCode;
	}

	public static void main(String[] args) {
		try {
			List<Object> lstObj = new TblSponsorHome().listAllObject(new TblSponsor());
			for (Object object : lstObj) {
				TblSponsor tblSponsor = (TblSponsor) object;
				tblSponsor.setSponsor_en_name(deAccent(tblSponsor.getSponsorName()));
				System.out.println(GsonUltilities.toJson(tblSponsor));
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
