package springboot.hbn.entities;

// default package
// Generated Aug 12, 2021, 11:35:37 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TransasctionRoom generated by hbm2java
 */
@Entity
@Table(name = "transasction_room")
public class TransasctionRoom implements java.io.Serializable {

	private Integer row_id;
	private String room_code;
	private String room_name;
	private int branch_id;
	private String address;
	private int status;
	private String manager;

	public TransasctionRoom() {
	}

	public TransasctionRoom(String roomCode, String roomName, int branchId, String address, int status,
			String manager) {
		this.room_code = roomCode;
		this.room_name = roomName;
		this.branch_id = branchId;
		this.address = address;
		this.status = status;
		this.manager = manager;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.row_id;
	}

	public void setRowId(Integer rowId) {
		this.row_id = rowId;
	}

	@Column(name = "room_code", nullable = false, length = 20)
	public String getRoomCode() {
		return this.room_code;
	}

	public void setRoomCode(String roomCode) {
		this.room_code = roomCode;
	}

	@Column(name = "room_name", nullable = false, length = 150)
	public String getRoomName() {
		return this.room_name;
	}

	public void setRoomName(String roomName) {
		this.room_name = roomName;
	}

	@Column(name = "branch_id", nullable = false)
	public int getBranchId() {
		return this.branch_id;
	}

	public void setBranchId(int branchId) {
		this.branch_id = branchId;
	}

	@Column(name = "address", nullable = false, length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "manager", nullable = false, length = 100)
	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

}
